### ISSUE TITLE
Capture

### ISSUE THREAD

**Issue by abdkaviani** [kyriesent/node-rtsp-stream#15]
Hi again

Now, I'm monitoring DVR camera by your project through web. It's Perfect
I have a question. Can I capture from stream video and save it as jpg, for example every 1 min?

Thanks a lot

**Comment by kyriesent** [comment]
You can't do that with this library. I'm not sure what would be the best way to do it. I would look into ffmpeg and/or imagemagick. Both of them have support for converting videos into other formats, and I'm pretty sure at least one of them will be able to do what you're looking for.
