### ISSUE TITLE
Does this include audio?

### ISSUE THREAD

**Issue by taimooralam** [kyriesent/node-rtsp-stream#2]
Is there an option to play audio in browser? The audio codec in AAC.

**Comment by kyriesent** [comment]
Unfortunately, this library doesn't support audio. JSMPEG is a purely
graphical library.

If you know of any libraries that can take audio over websocket and play
it, feel free to fork. However, chances are there are technologies
dedicated to streaming audio that will do that a whole lot better.

On Tue, Jan 12, 2016 at 2:36 AM, Taimoor Alam <notifications@github.com>
wrote:

> Is there an option to play audio in browser? The audio codec in AAC
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kyriesent/node-rtsp-stream/issues/2>.
>



-- 
What good is it if a man gains the entire world, yet forfeits his soul?
