### ISSUE TITLE
Why does node call three ffmpegs

### ISSUE THREAD

**Issue by yingqiang006** [kyriesent/node-rtsp-stream#21]
There are three ffmpegs in the task manager

**Comment by kyriesent** [comment]
HI @yingqiang006, I'm not seeing the same issue using the test code from the documentation. Each stream that you use will invoke ffmpeg a separate time. I'm not sure that ffmpeg is able to simultaneously handle multiple streams and output them to different destinations all from one invocation.

If this doesn't help, can you paste in some source code to reproduce the error?

**Comment by kyriesent** [comment]
Closing for now; let me know if this resurfaces!
