### ISSUE TITLE
how to set the ffmpegPath

### ISSUE THREAD

**Issue by tanbing0809** [kyriesent/node-rtsp-stream#22]

**Comment by ctrlMySoul** [comment]
i will use it in electron , i want set the path , please help me

**Comment by Noelfhim** [comment]
Hi,

I needed to set this path and also to override the "-f mpeg1video" parameter so I made some changes in my version.

I can submit this changes to you if want in a pull request. I made them in order to have backward compatibility.

**Comment by kyriesent** [comment]
@Noelfhim sorry for the delay, but if you're still open to making a pull request I'd be happy to review it. Thank you!!

**Comment by shealan** [comment]
@regisgrison could you submit a pull request? Setting the ffmpeg path would be invaluable for Electron developers that want to embed ffmpeg in their application binaries.

**Comment by regisgrison** [comment]
Sorry, I did not saw @kyriesent message.

Now I have to find the version where I made the changes. I'll try to do it as quick as possible.

**Comment by shealan** [comment]
@regisgrison thank you so much :)

**Comment by regisgrison** [comment]
Pull request done.

I did not commit -f override because it has changed since I did it and I don't think it was the change you asked for.

**Comment by shealan** [comment]
@regisgrison thank you!

**Comment by kyriesent** [comment]
Closed by #50
