### ISSUE TITLE
When executing ffmpeg I obtain : No such file or directory

### ISSUE THREAD

**Issue by gsanz** [kyriesent/node-rtsp-stream#24]
Hello when I execute the following stream of the example:
    stream = new Stream({
      name: 'name',
      streamUrl: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
      wsPort: 9999,
      ffmpegOptions: { // options ffmpeg flags
        '-stats': '', // an option with no neccessary value uses a blank string
        '-force_fps': 30, // options with required values specify the value after the key
      },

I have the follwing output 
: No such file or directory

I have been searching in ffmpeg about this problem and didn't find any solution. Any idea on it?
Thanks
Gorka

**Comment by nehoraigold** [comment]
I'm getting the same error. Any help would be appreciated!

**Comment by kyriesent** [comment]
Hi @gsanz and @nehoraigold, I managed to take a look at it and I think the `ffmpegOptions` are causing an issue. If you try using it without the options, the error should go away.

I'll need to take a look at trying to fix the options, but you can try that in the meantime and see if it helps!

**Comment by kyriesent** [comment]
Fixed by #25
