### ISSUE TITLE
Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by anllyksell** [kyriesent/node-rtsp-stream#28]
Hello,

First, thank you for your effort. When I try to run my serverside api.js I always get 'Error: spawn ffmpeg ENOENT' error. I couldn't find a solution. I use Windows pc. Does it matter ? If you can respond I wil be really glad.

**Comment by anllyksell** [comment]
And my api.js code is this : 

Stream = require("node-rtsp-stream");
stream = new Stream({
	name: "name",
	streamUrl: myurl,
	wsPort: 9999,
	ffmpegOptions: {
		// options ffmpeg flags
		"-stats": "", // an option with no neccessary value uses a blank string
		"-r": 30 // options with required values specify the value after the key,
	}
});

**Comment by kyriesent** [comment]
ENOENT usually means that node is trying to run a command that doesn't exist. Are you sure you have ffmpeg installed?

**Comment by anllyksell** [comment]
It was and its path was clear. I'm using Windows. On Linux without needing anything else it worked. But on Windows I needed to put ffmpeg.exe into project folder. I didn't understand why it was different on differend os. But it worked. You can close issue if you want. Thank you for your response :)

**Comment by amazing-wood** [comment]
Same problem，using windows and cannot find the ffmpeg，but I dont wanna copy ffmpeg.exe to the project folder. How could I set the config to let the project find the ffmpeg?

**Comment by JudyCCC** [comment]
how to get ffmpeg.exe?

**Comment by JudyCCC** [comment]
> how to get ffmpeg.exe?



> how to get ffmpeg.exe?

I got it, thank you

**Comment by kyriesent** [comment]
Should be closed by #50
