### ISSUE TITLE
Is there a demo?

### ISSUE THREAD

**Issue by kmax1940** [kyriesent/node-rtsp-stream#3]
Hello, is there a live demo of this working? Someone I know was going to use this but they said the video quality was not good.  I wonder if it might have been something they were doing so I would like to see someone else's implementation of this.

**Comment by kyriesent** [comment]
For jsmpeg quality demos, head over here:
https://github.com/phoboslab/jsmpeg . Notably:
http://phoboslab.org/files/jsmpeg/

Unfortunately there isn't a demo of this particular library and there's not
a lot of time on my hands right now to put one together.

Quality will largely depend on the compression rate you use in ffmpeg for
compressing the video. Feel free to fork and experiment.

On Sat, Jan 30, 2016 at 7:51 AM, kmax1940 <notifications@github.com> wrote:

> Hello, is there a live demo of this working? Someone I know was going to
> use this but they said the video quality was not good I wonder if it might
> have been something they were doing so I would like to see someone else's
> implementation of this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kyriesent/node-rtsp-stream/issues/3>.
>



-- 
What good is it if a man gains the entire world, yet forfeits his soul?
