### ISSUE TITLE
Add option for wsHost

### ISSUE THREAD

**Issue by SirSaar** [kyriesent/node-rtsp-stream#34]
https://github.com/kyriesent/node-rtsp-stream/blob/d2bb3f5a34e7b556045ecbc561165d9e8315038d/videoStream.js#L19

when you want to use several sockets on the same server you must use this option in order to segment each Websocket to diffrent Url. 
Correct me if i'm wrong.

**Comment by kyriesent** [comment]
Are you asking how to create multiple streams? You can use a different port for each stream, and they can all live on the same host.

There isn't any action to be taken here, so closing for now.
