### ISSUE TITLE
Does this module support RTSP authorization verification?

### ISSUE THREAD

**Issue by xiaojinhe2** [kyriesent/node-rtsp-stream#38]
Some cameras' RTSPs require authorization to access them. Now this module seems to be not authorized to access RTSP.

**Comment by kyriesent** [comment]
I think you can do this in the rtsp:// url.

https://stackoverflow.com/questions/27223873/set-username-password-in-rtsp-url#46825436

**Comment by kyriesent** [comment]
This is really a question about ffmpeg, not this module.
