### ISSUE TITLE
blurry video stream

### ISSUE THREAD

**Issue by akashhnag** [kyriesent/node-rtsp-stream#39]
This particular version (0.0.8) gives blurry videos. The problem gets solved if I use version 0.0.5.

**Comment by kyriesent** [comment]
Hm, not sure how to diagnose this. My quickest guess would be a change in ffmpeg options; the data coming through should otherwise be the same.

JSMPEG should also be decoding roughly the same.

Do you have a sample video stream to point to that you've seen this happen with?

**Comment by decioschmitt** [comment]
> This particular version (0.0.8) gives blurry videos. The problem gets solved if I use version 0.0.5.

I had the same issue.

**Comment by pooyasa** [comment]
I managed to load buckbunny on 0.0.5 but The problem with it, is it cannot connect to my camera. though 0.0.8 and vlc player work perfectly.

Here's the error:
`
[rtsp @ 0x1ad7410] Nonmatching transport in server reply
rtsp://[USER]:[Password]@192.168.1.100:554/onvif2: Invalid data found when processing input
RTSP stream exited with error
`

**Comment by pooyasa** [comment]
![image](https://user-images.githubusercontent.com/50808977/62376354-b3820100-b555-11e9-8ee8-18adaae76cb0.png)

**Comment by TKasperczyk** [comment]
> This is how it looks
> ![image](https://user-images.githubusercontent.com/50808977/62376354-b3820100-b555-11e9-8ee8-18adaae76cb0.png)

I'm also having this problem. The ffmpeg process in my case looks like this:
`ffmpeg -rtsp_transport tcp -thread_queue_size 512 -r 30 -i rtsp://1.2.3.4:554/profile2 -f mpegts -codec:v mpeg1video -stats -r 30 -`

To test if it's a problem on the ffmpeg part, I changed the output to `output.mp4` and then played the file through VLC. Everything looked fine. I guess there's something wrong either with the mpeg1muxer on the server side or jsmpeg on the client side.

**Comment by kyriesent** [comment]
Thanks again @TKasperczyk !

**Comment by jhanmarc** [comment]
Thank you @TKasperczyk !

**Comment by Aditya-Ace** [comment]
Finally, It worked. Why didn't I come here before! 
Thanks alot.
