### ISSUE TITLE
Restart Stream If RTSP back online

### ISSUE THREAD

**Issue by qahtansaid** [kyriesent/node-rtsp-stream#44]
Hi I'm a beginner . I want to make reconnection if RTSP back online without restarting node server, i've tried with PM2 and forever but it restart the node server and ffmpeg terminal keeps popping out. Help pls

**Comment by felipebutcher** [comment]
this is working out of box for me. if i kill the server and run again the stream continues automatically.

**Comment by kyriesent** [comment]
This seems to be resolved so I am closing. Feel free to open another issue if need be.

**Comment by hongson23** [comment]
hello @kyriesent 
I tested with the situation, while node server was processing so RTSP was down(about 2-3 minutes) after that it back online node server still working, I can see log information in terminal but jsmpeg can not show anythings on the clients
pls help! thanks
