### ISSUE TITLE
error when hosting on microsoft azure

### ISSUE THREAD

**Issue by xwOOtx** [kyriesent/node-rtsp-stream#46]
Hi,

I am able to run my nodejs application locally on a windows pc.

making use of node-rtsp-stream, backend retrieve a RTSP stream online and my front end display the stream.

however I am having trouble after deploying it into microsoft azure, seeing Error: spawn ffmpeg ENOENT in my azure's log. (I have also tried to include ffmpeg.exe into my app)

How should i go about 'installing' FFMPEG for deployment to microsoft azure?

**Comment by xwOOtx** [comment]
will appreciate it if anyone can advice on this.

Thanks

**Comment by felipebutcher** [comment]
just install ffmpeg... check if you are able to run "ffmpeg" on the command line

**Comment by kyriesent** [comment]
@xwOOtx closing for now. If you still have questions on this you can continue to comment.
