### ISSUE TITLE
NPM version v0.0.8

### ISSUE THREAD

**Issue by eeertekin** [kyriesent/node-rtsp-stream#47]
Hey,

Could you please push a new version to NPM? 

Latest version is [v0.0.8](https://www.npmjs.com/package/node-rtsp-stream) on NPM but it has errors that lead to crash on server. 
It's already fixed on master branch but package is not available on NPM.

Thank you!

https://github.com/kyriesent/node-rtsp-stream/commit/4c82465e5c6b50524ea416b2f5779a062e678be0#diff-9ff6f769dd6b0da8294d5320b34c5987

**Comment by kyriesent** [comment]
@eeertekin v0.0.9 is now available. Thanks for your patience!
