### ISSUE TITLE
websocket connection error

### ISSUE THREAD

**Issue by xwOOtx** [kyriesent/node-rtsp-stream#49]
Hi,
i am getting a "websocket connection to 'ws://localhost:9999/' failed" when I try to browse it on a browser. what ip/url should i configure for both ffmpeg config and jsmpeg?

Thanks

**Comment by kyriesent** [comment]
Not sure what the problem is, but see example:

```
Stream = require('node-rtsp-stream')
stream = new Stream({
  name: 'name',
  streamUrl: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
  wsPort: 9999,
  ffmpegOptions: { // options ffmpeg flags
    '-stats': '', // an option with no neccessary value uses a blank string
    '-r': 30 // options with required values specify the value after the key
  }
})
```

The `wsPort` option must match whatever port you use in browser. Beyond this I'm not sure what other things might help. Thanks!

**Comment by kyriesent** [comment]
Also look at #37 I think someone posted a solution there.
