### ISSUE TITLE
JSMpeg player not showing

### ISSUE THREAD

**Issue by xwOOtx** [kyriesent/node-rtsp-stream#51]
Hi, I am able to run the project successfully.  I am now trying to adapt it into an angular project. adding the client code in component.html doesn't show the jsmpeg player canvas. I got no errors in console.
my ws server stream is working as I am able to stream using the same client code on another non angular .html.

Thanks

**Comment by kyriesent** [comment]
Unfortunately I don't have any angular experience so I'm not going to be much use.

This seems to be resolved for now so I am closing. Feel free to open another issue if need be.
