### ISSUE TITLE
-rtsp_transport  tcp need to put before '-i'

### ISSUE THREAD

**Issue by dmwhw** [kyriesent/node-rtsp-stream#53]
-rtsp_transport  tcp need to put before '-i'.but options all put behind ‘-i’

**Comment by labmorales** [comment]
Submitted a fix with those parameters #54

**Comment by kyriesent** [comment]
I've merged #54. As far as you know, is there any downside to forcing TCP? Seems like there are very few streams that use UDP now for RTSP but I'm not sure. Any feedback is appreciated, thanks!

**Comment by dmwhw** [comment]
> 
> 
> I've merged #54. As far as you know, is there any downside to forcing TCP? Seems like there are very few streams that use UDP now for RTSP but I'm not sure. Any feedback is appreciated, thanks!

i think it is a good idea to  provides a option for user fill before "-i". as far as you know , there are other options ,such as "hwaccel " , which might be filled before "-i";
just like this...


`    this.spawnOptions = [
         ...this.preAdditionalFlagsBefore,
         "-i",
        
        "\""+this.url +"\"", //url
        '-f', 'mpegts', '-codec:v', 'mpeg1video',
        // additional ffmpeg options go here
        ...this.additionalFlags, '-'
    ]`
