### ISSUE TITLE
How to stream multiple rtsp in the same port

### ISSUE THREAD

**Issue by spksoft** [kyriesent/node-rtsp-stream#56]
How to stream multiple rtsp in the same port ?

I have to stream multiple RTSP link from multiple RTSP and I have many client to view diferrent and multiple rtsp sametime. Is this lib support this case ?

**Comment by ivanantunes** [comment]
I have this same doubt.

I'm using like this:
``` javascript
const getUrl = cams.map (c => c.URL);
const getTitle = cams.map (c => c.CamName);
const stream = new Stream ({
             name: getTitle,
             streamUrl: getUrl,
             wsPort: 9999,
             ffmpegOptions: {
                 '-stats': '',
                 '-r': 30
             }
         });
```

It looks like you can pass an array of **URL** so I still don't know how to access them. I'm using **JSMpeg** to display on the frontend. But I still couldn't display multiple rtsp cameras.

**Comment by spksoft** [comment]
@ivanantunes I think you cannot set a streamUrl as a array of string because from the `mpeg1muxer.js ` file line 11 there does not extract any array. From the code I sure that streamUrl must be string only.

**Comment by ivanantunes** [comment]
@spksoft you're right, I had to open several ports to stream.

```javascript
let setPort = 9000;
     cams.map (cam => {
         createConnection (cam.URL, cam.CamName, setPort);
         return setPort + = 1;
     });

function createConnection (url: string, title: string, port: number) {
     return new Stream ({
         name: title,
         streamUrl: url,
         wsPort: port,
         ffmpegOptions: {
             '-stats': '',
             '-r': 30
         }
     });
}
```
I'm reading my posts from a **.ini** in case I get an array of **"cameras"** where the url and name are. I don't know if so and a good way to do it. more is working for me right now.

**Comment by kyriesent** [comment]
@spksoft This is correct. Each RTSP stream will need its own port.

If there is enough demand for this I'm open to considering adding multiple streams/port as a feature. However, it might cause some breaking interface changes so it'd need to be a compelling case.

**Comment by Dipenduroy** [comment]
@kyriesent Can you add the multiple rtsp support in the same port? I am using [https://github.com/k-yle/rtsp-relay#usage-with-many-cameras](https://github.com/k-yle/rtsp-relay#usage-with-many-cameras) for the same functionality, but i am unable to get best video quality in it compared to your **node-rtsp-stream** library. I tried the suggested [options](https://github.com/k-yle/rtsp-relay#improving-the-video-quality) in the library but it didn't improve the video quality. Do we have any options to get multiple rtsp in the same port with better video quality?
