### ISSUE TITLE
Possible to get it off localhost? 

### ISSUE THREAD

**Issue by mmeyers-solartech** [kyriesent/node-rtsp-stream#58]
I notice that only client connections coming in via Localhost are recognized and served. The FFMPEG configurations seem to be using the standard defaults, but I was hoping to be able to recognize those client connections from either other devices on my local network or devices off network accessing via IP. These clients will end up being jsmpeg react components, Localhost jsmpeg components work swimmingly but nothing is making it outside of localhost.

**Comment by tamaker** [comment]
not sure if this is still an issue for you but I was able to open ports assigned to each node app instance on my router and have off prem access.
