### ISSUE TITLE
Failded to setup RTSP stream server

### ISSUE THREAD

**Issue by 3t-dev** [kyriesent/node-rtsp-stream#6]
Dear @kyriesent , I have a issue when setup rtsp stream server.
My code stream-server.js:
`Stream = require('node-rtsp-stream');`
`stream = new Stream({`
    `name: 'name',`
    `streamUrl: 'rtsp://192.168.83.47:8554/faded',`
    `wsPort: 9999`
`});`
That rtsp url is working properly on VLC Player.
When I start server with `node stream-server.js`, It's failed and show error ouput as below:
ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
  configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[rtsp @ 0x2101360] method SETUP failed: 461 Client error
rtsp://192.168.83.47:8554/faded: Protocol not supported

Please help me correct it.
Thanks so much.

**Comment by kyriesent** [comment]
@3t-dev I'm not sure from the output. I'm not really an expert in reading FFMPEG errors/output, but from the looks of it it's having trouble reading rtsp.

Does it work for you when trying another rtsp stream source, like [this test](https://github.com/kyriesent/node-rtsp-stream/blob/master/test/tests.coffee)? If it's not working for that either, you might need to recompile FFMPEG to make sure it will handle RTSP streams correctly.

If it does work, then it might be some setting in the stream itself. I'm not familiar enough w/ RTSP to be able to give you an educated answer on that 😞  Sorry!

PS. Don't know if this will help, but might also be a place to start: [google search](https://www.google.com/search?espv=2&q=ffmpeg+%22protocol+not+supported%22&oq=ffmpeg+%22protocol+not+supported%22&gs_l=serp.3...5354.8753.0.8905.2.2.0.0.0.0.74.137.2.2.0....0...1c.1.64.serp..0.0.0.pBeg5iO7sK4)

**Comment by 3t-dev** [comment]
Thanks you for reply, I have tried your test, but it's same error.
Maybe that're problems of ffmpeg library on my system and I must try to fix it.

**Comment by mtvbrianking** [comment]
If you're getting Error: `Uncaught Sync Token not found`, I it's mostly to be an issue with jsmpeg and its address [here] (https://github.com/phoboslab/jsmpeg/issues/112)

**Comment by kyriesent** [comment]
Stale issue, closing.
